kind: pipeline
type: docker
name: build

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: reg.phazor.works/gigafyde/image-gen
      registry: reg.phazor.works
      tags: latest
      force_tag: true
  - name: discord-notify
    image: appleboy/drone-discord
    when:
      status:
        - success
        - failure
    settings:
      message: "{{#success build.status}} ✅ Build #{{build.number}} of `{{repo.name}}` succeeded and deployed to production. {{else}} ❌ Build #{{build.number}} of `{{repo.name}}` failed. {{/success}}\n"
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token