kind: pipeline
type: docker
name: build

steps:
  - name: build-notify
    image: appleboy/drone-discord
    settings:
      message: "ℹ️ Build #{{build.number}} of `{{repo.name}}` on branch: ``{{build.branch}}` started"
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token

  - name: docker-build
    image: plugins/docker
    settings:
      repo: gigafyde/image-gen
      username: gigafyde
      password:
        from_secret: docker_token
      tags: latest
      force_tag: true
    when:
      branch:
        - master

  - name: dev-docker-build
    image: plugins/docker
    settings:
      repo: gigafyde/image-gen
      username: gigafyde
      password:
        from_secret: docker_token
      tags: dev
      force_tag: true
    when:
      branch:
        - dev

  - name: discord-notify
    image: appleboy/drone-discord
    when:
      status:
        - success
        - failure
    settings:
      message: "{{#success build.status}} ✅ Build #{{build.number}} of `{{repo.name}}` succeeded\n {{else}} ❌ Build #{{build.number}} of `{{repo.name}}` failed\n {{/success}}\n"
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
